### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by nolim-sysu** [LinGuanfu/SDIDS#13]
1. 损伤识别更改计算模型时，结果图没有清除

2. 损伤识别结果图的标题栏与模态识别结果标题栏名字一样
![1](https://user-images.githubusercontent.com/54575986/64961389-ff032b00-d8c7-11e9-9f68-30313abd0929.png)

3. 从损伤识别切换成模态分析时，结果图没有清除
![2](https://user-images.githubusercontent.com/54575986/64961563-65884900-d8c8-11e9-9cab-43cd8b4f3d48.png)

4. 损伤识别完进行模态分析时，结果图没有清除，并堆叠到频率表下方
![3](https://user-images.githubusercontent.com/54575986/64962296-bb112580-d8c9-11e9-992a-fa4ec4fde388.png)

5. 模态分析更改方法时，模型和结果图都没有清除
![4](https://user-images.githubusercontent.com/54575986/64962395-e98f0080-d8c9-11e9-91f2-84eb5ea5fdb2.png)

**Comment by LinGuanfu** [comment]
All bugs have been fixed, related to commits 8624650adff48d8a5e7f4f93ee529545eadcdde9 64f75c5ab6f86822e1eb6448702e334454386b87 73ba89dff30adbccc2aa070be2d02209e7c5c1cb bd4a6dc0b0b58349015d0e4027b535c38d6b9a4c f8f0793ca287f19e945b82fd4960dcc9d8f8c6f0.
